### ISSUE TITLE
Installation fails on MacOs Monterrey...

### ISSUE THREAD

**Issue by cbwilliamsnh** [coretech/terrafile#11]
❯ brew tap coretech/terrafile && brew install terrafile
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
cxgo                             gokart                           naml                             opentelemetry-cpp                tinysearch                       xpipe
==> Updated Formulae
Updated 81 formulae.
==> Updated Casks
Updated 59 casks.

==> Tapping coretech/terrafile
Cloning into '/usr/local/Homebrew/Library/Taps/coretech/homebrew-terrafile'...
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 33 (delta 0), reused 7 (delta 0), pack-reused 26
Receiving objects: 100% (33/33), 7.79 KiB | 7.79 MiB/s, done.
Resolving deltas: 100% (5/5), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/coretech/homebrew-terrafile/Formula/terrafile.rb
terrafile: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the coretech/terrafile tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/coretech/homebrew-terrafile/Formula/terrafile.rb:6

Error: Cannot tap coretech/terrafile: invalid syntax in tap!

**Comment by nahueloyha** [comment]
Same happened to me today, I'm proposing a fix to this issue in the following PR: https://github.com/coretech/homebrew-terrafile/pull/3

**Comment by nahueloyha** [comment]
Yes, now it's working! Thanks 😄
